title: EcoRedux Wiki
description: A wiki for EcoRedux storing all of the information needed!
theme: just-the-docs

url: https://wiki.ecoredux.net

aux_links:
  Wiki on Github: https://github.com/EcoRedux/EcoRedux-Wiki
color_scheme: dark
logo: "/assets/images/ecoredux.png"
favicon_ico: "/assets/images/favicon.ico"