title: EcoRedux Wiki
description: A wiki for EcoRedux storing all of the information needed!
theme: just-the-docs

url: https://wiki.ecoredux.net
color_scheme: dark
logo: "/assets/images/ecologo.png"
favicon_ico: "/assets/images/favicon.ico"